title = "Advances in Accounting, Management, Business and Economics Journal"
baseURL = "https://aambe-journal.org"
languageCode = "en-US"
theme = "Advances in Accounting, Management, Business and Economics Journal"

# The site's parameters
[params]
  home = "Home"
  abbreviatedTitle = "AAMBE Journal"
  description = "The Advances in Accounting, Management, Business and Economics Journal is an open-access, peer-reviewed academic journal published by the Department of Business Adminstration, Ahmadu Bello University, Zaria - Nigeria. This journal, which is published quarterly invites authors who wish to publish their works in the fields of Accounting, Management, Business Adminstration, Economics, Human Resource Management, Organisational Behaviour, Public Adminstration, Actuarial Science and Marketing."
  favicon = "img/favicon.png"
  mirrorfor = ""
  eISSN = "XXXX-XXXX"
  printISSN = "XXXX-XXXX"
  
  ## Publisher Information
  publisher = {name = "Episteme Health Inc.", city = "Melbourne", state = "Victoria", country = "Australia"}
  journalDOI = "10.xxxx/demo"
  publisherjournalabbreviation = "HSJT"
  subjects = ["Subject1", "Subject2"]
  crossmark_enabled = false
  
  ## Homepage image. Different sizes can be used to provide responsiveness.
  homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
    {img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
    {img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
  homepageimagefallback = "img/homepage_960w.jpg"
  homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"
  
  lenslogo = "img/lens-journal-logo.png"
  
  ## Set current issue or leave blank and the most recent issue will be used.
  currentissuepath = ""
  
  twittercard = "summary_large_image"
  twitterhandle = "@epistemehealth"
  socialimage = "img/twittercard.jpg"
  socialimagealt = "Health Sciences Journal Logo"
  socialdescription = "Advances in Accounting, Management, Business and Economics Journal Description"
  
  ## Set to true to load libraries from Cloudflare and Bootstrap CDNs where available. Otherwise leave blank.
  useCDN = false
  
  ## Custom blocks for the footer
  customblocks = [{ name = "ISSN Details", content = "ISBN XXXX-XXXX (Electronic)     "},
  {name = "License", content = "This theme is released under the GPL3 license."},
  {name = "Privacy Notice", content = "The only user information collected from this website will be used exclusively for the stated purposes of this journal and will not be made available for any other purpose or to any other party."},
  {name = "Contact Us", content = "[Associate Prof. Dr. Kabiru Jinjiri Ringim](https://orcid.org/0000-0002-4708-231X) (Managing Editor). Department of Business Adminstration, Ahmadu Bello University, Zaria - Nigeria. Email: kjringim@abu.edu.ng."}]

  
  
  
  [privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.disqus]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
  
  [menu]

    [[menu.main]]
      weight = 2
      name = "Articles"
      url = "current"
    [[menu.main]]
      weight = 3
      name = "Archives"
      url = "article"
    [[menu.main]]
      weight = 4
      name = "Submit"
      url = "about/submissions"
    [[menu.main]]
      weight = 5
      name = "About"
      hasChildren = true
    [[menu.main]]
      parent = "About"
      name = "About the Journal"
      url = "about/journal"
      weight = 6
    [[menu.main]]
      parent = "About"
      name = "Editorial Team"
      url = "about/editorial-team"
      weight = 7
    [[menu.main]]
      parent = "About"
      name = "Abstracting/Indexing"
      url = "about/abstracting-indexing"
      weight = 8
    [[menu.main]]
      parent = "About"
      name = "Contact"
      url = "contact"
      weight = 9

# Output formats
[mediaTypes]
  [mediaTypes."text/ris"]
    suffixes = ["ris"]
  [mediaTypes."text/bib"]
    suffixes = ["bib"]
  [mediaTypes."text/enw"]
    suffixes = ["enw"]
  [mediaTypes."text/latex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.galleyPDF]
    baseName = "view-pdf"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.galleyXML]
    baseName = "view-lens"
    isPlainText = true
    mediaType = "text/html"
    path = ""
  [outputFormats.customlens]
    baseName = "js/customlens"
    isPlainText = true
    mediaType = "application/javascript"
    path = ""
  [outputFormats.localfonts]
    baseName = "css/localfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.lensfonts]
    baseName = "css/lensfonts"
    isPlainText = true
    mediaType = "text/css"
    path = ""
  [outputFormats.exportris]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/ris"
    path = ""
  [outputFormats.exportbib]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/bib"
    path = ""
  [outputFormats.exportenw]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "text/enw"
    path = ""
  [outputFormats.exportcsljson]
    baseName = "export-citation"
    isPlainText = true
    mediaType = "application/json"
    path = ""

[outputs]
  home = ["HTML", "customlens", "localfonts", "lensfonts"]
  page = ["html", "galleyPDF", "galleyXML", "exportris", "exportenw", "exportbib", "exportcsljson" ]

[taxonomies]
  keyword = "keywords"
